version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: personalise
    ports:
      - "3306:3306"
      - "33060:33060"
    expose:
      - "3306"
    volumes:
      - ./Backend/migration.sql:/docker-entrypoint-initdb.d/migration.sql