apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: app-clusterrole
rules:
- apiGroups: [""]
  resources: ["pods", "services", "persistentvolumeclaims", "namespaces", "nodes"]
  verbs: ["get", "watch", "list", "create", "delete", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-rolebinding
  namespace: personalise
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: app-clusterrole
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:serviceaccounts
- kind: ServiceAccount
  name: personalise
  namespace: personalise

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: app-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: app-clusterrole
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:serviceaccounts
- kind: ServiceAccount
  name: personalise
  namespace: personalise

---