apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-personalise
          image: docker.io/glocker1v4/frontend-personalise:v10
          ports:
            - containerPort: 8080
          env:
            - name: VITE_API_URL
              value: "http://backend-personalise-personalise.apps.cluster-pfd66.dynamic.redhatworkshops.io/api"